USE HOSPITAL_DB;

CREATE TABLE DOCTORS (
    DOC_ID INT NOT NULL PRIMARY KEY,
    MAJOR_TREAT VARCHAR(25) NOT NULL,
    DOC_NAME VARCHAR(20) NOT NULL,
    DOC_GEN CHAR(1) NOT NULL,
    DOC_PHONE VARCHAR(15),
    DOC_EMAIL VARCHAR(50) UNIQUE,
    DOC_POSITION VARCHAR(20) NOT NULL
);

CREATE TABLE NURSES (
    NUR_ID INT NOT NULL PRIMARY KEY,
    NUR_JOB VARCHAR(25) NOT NULL,
    NUR_NAME VARCHAR(20) NOT NULL,
    NUR_GEN CHAR(1) NOT NULL,
    NUR_PHONE VARCHAR(15),
    NUR_EMAIL VARCHAR(50) UNIQUE,
    NUR_POSITION VARCHAR(20) NOT NULL
);

CREATE TABLE PATIENTS (
    PAT_ID INT NOT NULL PRIMARY KEY,
    NUR_ID INT,
    DOC_ID INT,
    PAT_NAME VARCHAR(20) NOT NULL,
    PAT_GEN CHAR(1) NOT NULL,
    PAT_JUMIN VARCHAR(14) NOT NULL,
    PAT_ADDR VARCHAR(100) NOT NULL,
    PAT_PHONE VARCHAR(15),
    PAT_EMAIL VARCHAR(50) UNIQUE,
    PAT_JOB VARCHAR(20) NOT NULL,
    FOREIGN KEY (NUR_ID) REFERENCES NURSES(NUR_ID),
    FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID)
);

CREATE TABLE TREATMENTS (
    TREAT_ID INT NOT NULL PRIMARY KEY,
    PAT_ID INT NOT NULL,
    DOC_ID INT NOT NULL,
    TREAT_CONTENTS VARCHAR(1000) NOT NULL,
    TREAT_DATE DATE NOT NULL,
    FOREIGN KEY (PAT_ID) REFERENCES PATIENTS(PAT_ID),
    FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID)
);

CREATE TABLE CHARTS (
    CHAT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    TREAT_ID INT NOT NULL,
    PAT_ID INT NOT NULL,
    DOC_ID INT NOT NULL,
    NUR_ID INT NOT NULL,
    CHAT_CONTENTS VARCHAR(1000) NOT NULL,
    FOREIGN KEY (TREAT_ID) REFERENCES TREATMENTS(TREAT_ID),
    FOREIGN KEY (PAT_ID) REFERENCES PATIENTS(PAT_ID),
    FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID),
    FOREIGN KEY (NUR_ID) REFERENCES NURSES(NUR_ID)
);

