
-- DEPT 테이블을 복사하여 DEPT_TEMP 테이블 생성
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

-- DEPT_TEMP 테이블 삭제
DROP TABLE DEPT_TEMP;

-- DEPT 테이블을 복사하여 다시 DEPT_TEMP 테이블 생성
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

-- DEPT_TEMP 테이블 삭제
DROP TABLE DEPT_TEMP;

-- DEPT 테이블을 복사하여 다시 DEPT_TEMP 테이블 생성
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

-- DEPT_TEMP 테이블에 새로운 부서 정보 추가
INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
VALUES(50, 'DATABASE','SEOUL');

-- DEPT_TEMP 테이블 내용 조회
SELECT * FROM DEPT_TEMP;

-- DEPT_TEMP 테이블에 두 번째 부서 정보 추가
INSERT INTO DEPT_TEMP
VALUES(60, 'NETWORK','BUSAN');

-- DEPT_TEMP 테이블에 세 번째 부서 정보 추가, LOC 값은 NULL
INSERT INTO DEPT_TEMP
VALUES(70, 'WEB',NULL);

-- 특정 컬럼만 지정하여 추가: 부서번호 90, 위치(INCHEON) 정보만 추가
INSERT INTO DEPT_TEMP(DEPTNO,LOC)
VALUES(90,'INCHEON');

-- EMP_TEMP 테이블을 구조만 복사 (데이터 없이) 생성
CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP WHERE 1 <> 1;

-- EMP_TEMP 테이블 내용 조회 (현재 비어 있음)
SELECT * FROM EMP_TEMP;

-- EMP_TEMP 테이블에 새로운 사원 정보 추가 (PRESIDENT)
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE,SAL,COMM,DEPTNO)
VALUES(9999, 'ARINA','PRESIDENT',NULL,'2001/01/01',5000,1000,10);

-- EMP_TEMP 테이블 내용 조회
SELECT * FROM EMP_TEMP;

-- EMP_TEMP 테이블에 새로운 사원 정보 추가 (MANAGER)
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE,SAL,COMM,DEPTNO)
VALUES(1111, 'ALICE','MANAGER',9999,'2001-01-05',4000,NULL,20);

-- EMP_TEMP 테이블 내용 조회
SELECT * FROM EMP_TEMP;

-- 잘못된 INSERT 쿼리 (날짜 형식 오류 주석 처리됨)
-- INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE,SAL,COMM,DEPTNO)
-- VALUES(1211, 'ICE','MANAGER',9999,'07/01/2001',4000,NULL,20);

-- STR_TO_DATE 함수로 올바른 날짜 형식으로 사원 정보 추가
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE,SAL,COMM,DEPTNO)
VALUES(1211, 'EVA','MANAGER',9999,STR_TO_DATE('07/01/2001','%d/%m/%Y'),4000,NULL,20);

-- EMP_TEMP 테이블 내용 조회
SELECT * FROM EMP_TEMP;

-- SYS_DATE() 함수를 사용하여 현재 날짜로 새로운 사원 정보 추가 (MANEGER 오타 있음)
INSERT INTO EMP_TEMP(EMPNO,ENAME, JOB, MGR, HIREDATE,SAL,COMM,DEPTNO)
VALUES(3111,'EDWARD','MANEGER',9999,SYSDATE(),4000,NULL,30);

-- EMP_TEMP 테이블 내용 조회
SELECT * FROM EMP_TEMP;

-- SALGRADE 테이블과 EMP 테이블을 조인하여 조건에 맞는 사원 정보 추가
INSERT INTO EMP_TEMP(EMPNO,ENAME, JOB, MGR, HIREDATE,SAL,COMM,DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE=1;

-- EMP_TEMP 테이블 내용 조회
SELECT * FROM EMP_TEMP;

-- 'MANEGER' 직책을 가진 사원 조회 (오타 확인)
SELECT * FROM EMP_TEMP WHERE JOB = 'MANEGER';

-- 오타 수정: 'MANEGER' -> 'MANAGER'로 수정
UPDATE EMP_TEMP
SET JOB = 'MANAGER'
WHERE EMPNO = 3111;

-- 수정된 사원 정보 확인
SELECT * FROM EMP_TEMP WHERE EMPNO = 3111;

-- 동일한 쿼리로 'MANEGER' -> 'MANAGER' 수정 (다시 실행)
UPDATE EMP_TEMP
SET JOB = 'MANAGER'
WHERE EMPNO = 3111;

-- 여전히 'MANEGER' 직책을 가진 사원이 있는지 확인
SELECT * FROM EMP_TEMP WHERE JOB = 'MANEGER';

-- 'MANEGER'로 등록된 사원 정보 삭제
DELETE FROM EMP_TEMP
WHERE EMPNO = 3111;

-- 삭제된 사원의 정보 다시 추가 (올바른 직책 'MANAGER'로 추가)
INSERT INTO EMP_TEMP(EMPNO,ENAME, JOB, MGR, HIREDATE,SAL,COMM,DEPTNO)
VALUES(3111,'EDWARD','MANAGER',9999,SYSDATE(),4000,NULL,30);
