USE SCOTT;

-- 10-2
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT; -- DEPT 테이블의 모든 데이터를 복사하여 DEPT_TEMP2 테이블을 생성

SELECT * FROM DEPT_TEMP2; -- DEPT_TEMP2 테이블의 모든 데이터를 조회

set sql_safe_updates=0; -- 안전 업데이트 모드를 비활성화하여 테이블 업데이트 가능하도록 설정

UPDATE DEPT_TEMP2
SET LOC='SEOUL'; -- DEPT_TEMP2 테이블의 모든 행에 대해 LOC 값을 'SEOUL'로 업데이트

SELECT * FROM DEPT_TEMP2; -- DEPT_TEMP2 테이블의 모든 데이터를 조회하여 변경 사항 확인

ROLLBACK; -- 변경 사항을 롤백하여 이전 상태로 복원

UPDATE DEPT_TEMP2
SET DNAME='DATABASE',
	LOC='SEOUL'
WHERE DEPTNO=40; -- DEPTNO가 40인 행의 DNAME을 'DATABASE'로, LOC를 'SEOUL'로 업데이트

SELECT * FROM DEPT_TEMP2; -- 변경 사항을 확인하기 위해 DEPT_TEMP2 테이블을 조회

UPDATE DEPT_TEMP2
SET DNAME=(SELECT DNAME FROM DEPT WHERE DEPTNO=40),
	LOC=(SELECT LOC FROM DEPT WHERE DEPTNO=40)
WHERE DEPTNO=40; -- DEPT 테이블의 데이터를 이용해 DEPTNO가 40인 DEPT_TEMP2 행의 DNAME과 LOC를 업데이트

SELECT * FROM DEPT_TEMP2; -- 변경 사항을 확인하기 위해 DEPT_TEMP2 테이블을 조회

UPDATE DEPT_TEMP2
SET LOC='SEOUL'
WHERE DEPTNO=
(
SELECT TEMP.DEPTNO FROM 
(SELECT DEPTNO AS DEPTNO FROM DEPT_TEMP2 WHERE DNAME='OPERATIONS') 
AS TEMP
); -- DNAME이 'OPERATIONS'인 부서의 DEPTNO를 이용해 LOC를 'SEOUL'로 업데이트

SELECT * FROM DEPT_TEMP2; -- 변경 사항을 확인하기 위해 DEPT_TEMP2 테이블을 조회

SELECT * FROM DEPT_TEMP2 WHERE DEPTNO=40; -- DEPTNO가 40인 행을 조회하여 변경된 내용 확인

-- 10-3

CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP; -- EMP 테이블의 데이터를 복사하여 EMP_TEMP2 테이블을 생성

SELECT * FROM EMP_TEMP2; -- EMP_TEMP2 테이블의 모든 데이터를 조회

DELETE FROM EMP_TEMP2
WHERE JOB='MANAGER'; -- JOB이 'MANAGER'인 행을 EMP_TEMP2 테이블에서 삭제

SELECT * FROM EMP_TEMP2; -- EMP_TEMP2 테이블의 모든 데이터를 조회하여 삭제 결과 확인

DELETE FROM EMP_TEMP2
WHERE EMPNO IN(
SELECT TEMP.EMPNO 
FROM(
SELECT E.EMPNO 
FROM EMP_TEMP2 E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE=3
AND DEPTNO=30
)
AS TEMP); -- SAL이 SALGRADE 테이블의 GRADE 3에 해당하고 DEPTNO가 30인 사원을 EMP_TEMP2 테이블에서 삭제

SELECT * FROM EMP_TEMP2; -- 삭제된 결과를 확인하기 위해 EMP_TEMP2 테이블을 조회

DELETE FROM EMP_TEMP2; -- EMP_TEMP2 테이블의 모든 데이터를 삭제

SELECT * FROM EMP_TEMP2; -- EMP_TEMP2 테이블을 조회하여 모든 데이터가 삭제되었는지 확인

-- -------------------

CREATE TABLE CHAP10HW_EMP SELECT * FROM EMP; -- EMP 테이블을 복사하여 CHAP10HW_EMP 테이블을 생성
CREATE TABLE CHAP10HW_DEPT SELECT * FROM DEPT; -- DEPT 테이블을 복사하여 CHAP10HW_DEPT 테이블을 생성
CREATE TABLE CHAP10HW_SALGRADE SELECT * FROM SALGRADE; -- SALGRADE 테이블을 복사하여 CHAP10HW_SALGRADE 테이블을 생성

-- Q1: CHAP10HW_DEPT 테이블에 50, 60, 70, 80번 부서를 등록하는 SQL
INSERT INTO CHAP10HW_DEPT(DEPTNO,DNAME,LOC)
VALUES
(50, 'ORACLE','BUSAN'),
(60, 'SQL','ILSAN'),
(70, 'SELECT','INCHEON'),
(80, 'DML','BUNDANG');

SELECT * FROM CHAP10HW_DEPT; -- CHAP10HW_DEPT 테이블의 모든 데이터를 조회하여 새로운 부서가 추가되었는지 확인

-- Q2: CHAP10HW_EMP 테이블에 8명의 사원의 정보를 등록하는 SQL
INSERT INTO CHAP10HW_EMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES
(7201,'TEST_USER1','MANAGER',7788,'2016-01-02',4500,NULL,50),
(7202,'TEST_USER2','CLERK',7788,'2016-02-21',1800,NULL,50),
(7203,'TEST_USER3','ANALYST',7788,'2016-04-11',3400,NULL,60),
(7204,'TEST_USER4','SALESMAN',7788,'2016-05-31',2700,NULL,60),
(7205,'TEST_USER5','CLERK',7788,'2016-07-20',2600,NULL,70),
(7206,'TEST_USER6','CLERK',7788,'2016-09-08',2600,NULL,70),
(7207,'TEST_USER7','LECTURER',7788,'2016-10-28',2300,NULL,80),
(7208,'TEST_USER8','STUDENT',7788,'2016-03-09',1200,NULL,80);

SELECT * FROM CHAP10HW_EMP; -- CHAP10HW_EMP 테이블의 데이터를 조회하여 사원들이 정상적으로 추가되었는지 확인

-- Q3: 급여가 DEPTNO 50의 평균 급여보다 높은 사원의 DEPTNO를 70으로 변경하는 SQL
UPDATE 
CHAP10HW_EMP 
SET DEPTNO=70
WHERE SAL > (
    SELECT AVG(E1.SAL) 
    FROM CHAP10HW_EMP E1 
    WHERE E1.DEPTNO = 50
);

SELECT * FROM CHAP10HW_EMP ORDER BY DEPTNO; -- 변경된 부서 번호를 기준으로 결과를 확인하기 위해 CHAP10HW_EMP 테이블을 조회

-- Q4: 부서 번호가 60인 부서에서 가장 빠른 입사일보다 늦게 입사한 사원의 급여를 10% 인상하고, 부서를 80번으로 변경하는 SQL
UPDATE CHAP10HW_EMP 
SET SAL=SAL*1.1,
	DEPTNO=80
WHERE HIREDATE > 
(
SELECT TEMP.MIN_HIREDATE 
FROM( SELECT MIN(E.HIREDATE) AS MIN_HIREDATE
FROM CHAP10HW_EMP E
WHERE E.DEPTNO=60)
AS TEMP);
SELECT * FROM CHAP10HW_EMP; -- 변경된 내용을 확인하기 위해 CHAP10HW_EMP 테이블을 조회

-- Q5: CHAP10HW_EMP에 속한 사원 중 급여 등급이 5인 사원을 삭제하는 SQL
DELETE FROM CHAP10HW_EMP E1
WHERE E1.EMPNO IN 
(SELECT TEMP.EMPNO 
FROM(SELECT E2.EMPNO AS EMPNO FROM CHAP10HW_EMP E2 
JOIN CHAP10HW_SALGRADE S 
ON (E2.SAL BETWEEN S.LOSAL AND S.HISAL) AND S.GRADE=5) 
AS TEMP);
SELECT * FROM CHAP10HW_EMP; -- 삭제된 결과를 확인하기 위해 CHAP10HW_EMP 테이블을 조회
